### ISSUE TITLE
Integrate SV Model

### ISSUE THREAD

**Issue by juanmc2005** [juanmc2005/SimilarityLearning#13]
Integrate the speaker verification model (provided) into the project. Make it available through an interface similar to the MNIST model.

**Comment by hbredin** [comment]
The best performance I got so far on VoxCeleb is with [ClopiNet](https://github.com/pyannote/pyannote-audio/blob/e1a5c1698f4471d2bbca6ff1cc6bb31e953d15a6/pyannote/audio/embedding/models/clopinet.py#L41) architecture on top of MFCC features.
A tutorial and pre-trained model is available [here](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding)

The issue with this model is that it relies on MFCC which are slow to compute: one cannot really precompute them because random noise is added on-the-fly to the audio file as a data augmentation step. Therefore, I have been trying recently to replace the MFCC features by trained [SincNet](https://github.com/mravanelli/SincNet) features (computed from the waveform directly) but to no avail so far.

Yet, I'd rather have you work directly from the waveform (looks cleaner).
So, unless I manage to switch ClopiNet to waveform quickly, I suggest you use the architecture provided in the SincNet [repo](https://github.com/mravanelli/SincNet).

**Comment by juanmc2005** [comment]
@hbredin Got it. A priori I'll work on integrating SincNet

**Comment by juanmc2005** [comment]
SincNet is working using our custom loss modules, like arc margin or congenerous cosine (CoCo).
A better implementation will probably come once VoxCeleb is integrated.
